1. How to load data?
2. How to work on csv / tsv file?
3. Basic Statistics on Data.
4. Data Cleaning with each column.
5. Choice description
6. Regular Expression
7. Solve some questions from dataset.

In [ ]:
# importing libraries
import numpy as np
import pandas as pd

## Read Data

In [ ]:
data = pd.read_csv("/content/Data-cleaning-for-beginners-using-pandas.csv")

In [ ]:
copy_data = data.copy()

In [ ]:
data

    Index   Age      Salary  Rating       Location  Established Easy Apply
0       0  44.0   $44k-$99k     5.4       India,In         1999       TRUE
1       1  66.0   $55k-$66k     3.5    New York,Ny         2002       TRUE
2       2   NaN   $77k-$89k    -1.0    New York,Ny           -1         -1
3       3  64.0   $44k-$99k     4.4       India In         1988         -1
4       4  25.0   $44k-$99k     6.4  Australia Aus         2002         -1
5       5  44.0   $77k-$89k     1.4       India,In         1999       TRUE
6       6  21.0   $44k-$99k     0.0    New York,Ny           -1         -1
7       7  44.0   $44k-$99k    -1.0  Australia Aus           -1         -1
8       8  35.0   $44k-$99k     5.4    New York,Ny           -1         -1
9       9  22.0   $44k-$99k     7.7       India,In           -1       TRUE
10     10  55.0   $10k-$49k     5.4       India,In         2008       TRUE
11     11  44.0   $10k-$49k     6.7       India,In         2009         -1
12     12   NaN   $44k-$99k     0.0       India,In         1999         -1
13     13  25.0   $44k-$99k    -1.0  Australia Aus         2019       TRUE
14     14  66.0   $44k-$99k     4.0  Australia Aus         2020       TRUE
15     15  44.0  $88k-$101k     3.0  Australia Aus         1999         -1
16     16  19.0   $19k-$40k     4.5       India,In         1984         -1
17     17   NaN   $44k-$99k     5.3    New York,Ny         1943       TRUE
18     18  35.0   $44k-$99k     6.7    New York,Ny         1954       TRUE
19     19  32.0   $44k-$99k     3.3    New York,Ny         1955       TRUE
20     20   NaN   $44k-$99k     5.7    New York,Ny         1944       TRUE
21     21  35.0   $44k-$99k     5.0    New York,Ny         1946         -1
22     22  19.0   $55k-$66k     7.8    New York,Ny         1988       TRUE
23     23   NaN   $44k-$99k     2.4    New York,Ny         1999       TRUE
24     24  13.0   $44k-$99k    -1.0    New York,Ny         1987         -1
25     25  55.0   $44k-$99k     0.0  Australia Aus         1980       TRUE
26     26   NaN   $55k-$66k     NaN       India,In         1934       TRUE
27     27  52.0   $44k-$99k     5.4       India,In         1935         -1
28     28   NaN   $39k-$88k     3.4  Australia Aus         1932         -1

In [ ]:
data.head()

   Index   Age     Salary  Rating       Location  Established Easy Apply
0      0  44.0  $44k-$99k     5.4       India,In         1999       TRUE
1      1  66.0  $55k-$66k     3.5    New York,Ny         2002       TRUE
2      2   NaN  $77k-$89k    -1.0    New York,Ny           -1         -1
3      3  64.0  $44k-$99k     4.4       India In         1988         -1
4      4  25.0  $44k-$99k     6.4  Australia Aus         2002         -1

In [ ]:
data.tail()

    Index   Age     Salary  Rating       Location  Established Easy Apply
24     24  13.0  $44k-$99k    -1.0    New York,Ny         1987         -1
25     25  55.0  $44k-$99k     0.0  Australia Aus         1980       TRUE
26     26   NaN  $55k-$66k     NaN       India,In         1934       TRUE
27     27  52.0  $44k-$99k     5.4       India,In         1935         -1
28     28   NaN  $39k-$88k     3.4  Australia Aus         1932         -1

In [ ]:
data.shape

(29, 7)

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29 entries, 0 to 28
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Index        29 non-null     int64
 1   Age          22 non-null     float64
 2   Salary       29 non-null     object
 3   Rating       28 non-null     float64
 4   Location     29 non-null     object
 5   Established  29 non-null     int64
 6   Easy Apply   29 non-null     object
dtypes: float64(2), int64(2), object(3)
memory usage: 1.7+ KB

In [ ]:
data.isnull().sum()

Index          0
Age            7
Salary         0
Rating         1
Location       0
Established    0
Easy Apply     0
dtype: int64

In [ ]:
data.columns

Index(['Index', 'Age', 'Salary', 'Rating', 'Location', 'Established',
       'Easy Apply'],
      dtype='object')

In [ ]:
sample = data.columns.str.lower().str.replace(" ","_")

In [ ]:
text = '$40k-$100k'
text.replace('$',"")

'40k-100k'

40-100

40000-100000

In [ ]:
sample

Index(['index', 'age', 'salary', 'rating', 'location', 'established',
       'easy_apply'],
      dtype='object')

## Age column

In [ ]:
avg_age = data['Age'].mean()
avg_age

39.04545454545455

In [ ]:
# fill the missing values with mean
data['Age'] = data.Age.fillna(avg_age)
data['Age'] = data.Age.round(decimals=1)

In [ ]:
data.head()

   Index   Age     Salary  Rating       Location  Established Easy Apply
0      0  44.0  $44k-$99k     5.4       India,In         1999       TRUE
1      1  66.0  $55k-$66k     3.5    New York,Ny         2002       TRUE
2      2  39.0  $77k-$89k    -1.0    New York,Ny           -1         -1
3      3  64.0  $44k-$99k     4.4       India In         1988         -1
4      4  25.0  $44k-$99k     6.4  Australia Aus         2002         -1

In [ ]:
data['Age']

0     44.0
1     66.0
2      NaN
3     64.0
4     25.0
5     44.0
6     21.0
7     44.0
8     35.0
9     22.0
10    55.0
11    44.0
12     NaN
13    25.0
14    66.0
15    44.0
16    19.0
17     NaN
18    35.0
19    32.0
20     NaN
21    35.0
22    19.0
23     NaN
24    13.0
25    55.0
26     NaN
27    52.0
28     NaN
Name: Age, dtype: float64

Replace

In [ ]:
data['Location'].value_counts()

New York,Ny      12
India,In          9
Australia Aus     7
India In          1
Name: Location, dtype: int64

In [ ]:
data['Location'] = data['Location'].replace({'New York,Ny':'New York', 'India,In':'India','India In':'India', 'Australia Aus':'Australia'})

In [ ]:
df['Location'] = df['Location'].str.replace(r'\sIn$', '')

In [ ]:
l = ['India','In']
l[1]

'In'

In [ ]:
data['Location'].str.split(",",expand=True)[0]

0             India
1          New York
2          New York
3          India In
4     Australia Aus
5             India
6          New York
7     Australia Aus
8          New York
9             India
10            India
11            India
12            India
13    Australia Aus
14    Australia Aus
15    Australia Aus
16            India
17         New York
18         New York
19         New York
20         New York
21         New York
22         New York
23         New York
24         New York
25    Australia Aus
26            India
27            India
28    Australia Aus
Name: 0, dtype: object

In [ ]:
df["Location"] = df["Location"].str.lower().str.replace(",", " " ).str.rstrip("in")

Location column

In [ ]:
data['Location'].str.lower().str.replace(",","").str.rstrip("in")

0             india
1        new yorkny
2        new yorkny
3            india
4     australia aus
5             india
6        new yorkny
7     australia aus
8        new yorkny
9             india
10            india
11            india
12            india
13    australia aus
14    australia aus
15    australia aus
16            india
17       new yorkny
18       new yorkny
19       new yorkny
20       new yorkny
21       new yorkny
22       new yorkny
23       new yorkny
24       new yorkny
25    australia aus
26            india
27            india
28    australia aus
Name: Location, dtype: object

In [ ]:
data['Location'].astype

<bound method NDFrame.astype of 0          India,In
1       New York,Ny
2       New York,Ny
3          India In
4     Australia Aus
5          India,In
6       New York,Ny
7     Australia Aus
8       New York,Ny
9          India,In
10         India,In
11         India,In
12         India,In
13    Australia Aus
14    Australia Aus
15    Australia Aus
16         India,In
17      New York,Ny
18      New York,Ny
19      New York,Ny
20      New York,Ny
21      New York,Ny
22      New York,Ny
23      New York,Ny
24      New York,Ny
25    Australia Aus
26         India,In
27         India,In
28    Australia Aus
Name: Location, dtype: object>

# What questions you can find in dataset 2(chipotle)?
Before you actually answer these questions i will assume you have performed data cleaning.

1. Quantity of each item? (Top 5 itmes available in store)
2. which is most ordered item in choice_description?
3. What is total order count?
4. What is reveneu?
5. what are number of orders?
6. Whta is average revenue amount per order?
7. How many different items are sold?
8. what is revenue from each product?


1. Find the unique items
2. Find total cost and quantity of every unique items
3. Find the average of every unique item
4. Replace the items if abnormal with avg

In [ ]:
df = pd.read_csv("/content/chipotle.tsv",sep='\t')
df

FileNotFoundError: ignored

In [43]:
['Tomatillo-Red Chili Salsa (Hot)', ['Black Beans', 'Rice', 'Cheese', 'Sour Cream']][0]

'Tomatillo-Red Chili Salsa (Hot)'